
CATEGORIES_JP = [
    "*",
    "空白",
    "補助記号",
    "句点",
    "一般",
    "名詞",
    "普通名詞",
    "助数詞可能",
    "動詞",
    "サ変可能",
    "助詞",
    "格助詞",
    "記号",
    "数詞",
    "副詞可能",
    "副詞",
    "固有名詞",
    "人名",
    "名",
    "ＡＡ",
    "顔文字",
    "括弧開",
    "形状詞可能",
    "括弧閉",
    "文字",
    "地名",
    "国",
    "形状詞",
    "サ変形状詞可能",
    "姓",
    "終助詞",
    "読点",
    "接尾辞",
    "名詞的",
    "助数詞",
    "非自立可能",
    "助動詞",
    "感動詞",
    "形容詞",
    "フィラー",
    "代名詞",
    "連体詞",
    "接頭辞",
    "タリ",
    "接続詞",
    "副助詞",
    "接続助詞",
    "動詞的",
    "形容詞的",
    "形状詞的",
    "係助詞",
    "助動詞語幹",
    "準体助詞",
]

CATEGORIES_EN = [
    "*",
    "Space",
    "Auxiliary symbol",
    "Period",
    "General",
    "Noun",
    "Ordinary noun",
    "Counter possible",
    "Verb",
    "Sa row irregular possible",
    "Particle",
    "Case particle",
    "Symbol",
    "Counter",
    "Adverb possible",
    "Adverb",
    "Proper noun",
    "Person's name",
    "First name",
    "AA",
    "Emoticon",
    "Open parentheses",
    "Adjectival noun possible",
    "Close parentheses",
    "Character",
    "Place name",
    "Country",
    "Adjectival noun",
    "Sa row irregular adjectival noun possible",
    "Surname",
    "Final particle",
    "Comma",
    "Suffix",
    "Noun-like",
    "Counter",
    "Can be dependent",
    "Auxiliary verb",
    "Interjection",
    "Adjective",
    "Filler",
    "Pronoun",
    "Conjunction",
    "Prefix",
    "Tari",
    "Conjunction",
    "Adverbial particle",
    "Conjunction particle",
    "Verb-like",
    "Adjective-like",
    "Adjectival noun-like",
    "Linking particle",
    "Auxiliary verb stem",
    "Quasi-subject particle",
]

CONJUGATION_TYPES_JP = [
    "*",
    "カ行変格",
    "サ行変格",
    "上一段-ア行",
    "上一段-カ行",
    "上一段-ガ行",
    "上一段-ザ行",
    "上一段-タ行",
    "上一段-ナ行",
    "上一段-ハ行",
    "上一段-バ行",
    "上一段-マ行",
    "上一段-ラ行",
    "下一段-ア行",
    "下一段-カ行",
    "下一段-ガ行",
    "下一段-サ行",
    "下一段-ザ行",
    "下一段-タ行",
    "下一段-ダ行",
    "下一段-ナ行",
    "下一段-ハ行",
    "下一段-バ行",
    "下一段-マ行",
    "下一段-ラ行",
    "五段-カ行",
    "五段-ガ行",
    "五段-サ行",
    "五段-タ行",
    "五段-ナ行",
    "五段-バ行",
    "五段-マ行",
    "五段-ラ行",
    "五段-ワア行",
    "助動詞-ジャ",
    "助動詞-タ",
    "助動詞-ダ",
    "助動詞-タイ",
    "助動詞-デス",
    "助動詞-ドス",
    "助動詞-ナイ",
    "助動詞-ナンダ",
    "助動詞-ヌ",
    "助動詞-ヘン",
    "助動詞-マイ",
    "助動詞-マス",
    "助動詞-ヤ",
    "助動詞-ヤス",
    "助動詞-ラシイ",
    "助動詞-レル",
    "形容詞",
    "文語カ行変格",
    "文語サ行変格",
    "文語ナ行変格",
    "文語ラ行変格",
    "文語上一段-ナ行",
    "文語上一段-マ行",
    "文語上一段-ワ行",
    "文語上二段-タ行",
    "文語上二段-ダ行",
    "文語上二段-ハ行",
    "文語上二段-バ行",
    "文語上二段-ヤ行",
    "文語上二段-ラ行",
    "文語下二段-ア行",
    "文語下二段-カ行",
    "文語下二段-ガ行",
    "文語下二段-サ行",
    "文語下二段-ザ行",
    "文語下二段-タ行",
    "文語下二段-ダ行",
    "文語下二段-ナ行",
    "文語下二段-ハ行",
    "文語下二段-バ行",
    "文語下二段-マ行",
    "文語下二段-ヤ行",
    "文語下二段-ラ行",
    "文語下二段-ワ行",
    "文語助動詞-キ",
    "文語助動詞-ケム",
    "文語助動詞-ケリ",
    "文語助動詞-ゴトシ",
    "文語助動詞-ザマス",
    "文語助動詞-ザンス",
    "文語助動詞-ジ",
    "文語助動詞-ズ",
    "文語助動詞-タリ-完了",
    "文語助動詞-タリ-断定",
    "文語助動詞-ツ",
    "文語助動詞-ナリ-伝聞",
    "文語助動詞-ナリ-断定",
    "文語助動詞-ヌ",
    "文語助動詞-ベシ",
    "文語助動詞-マジ",
    "文語助動詞-ム",
    "文語助動詞-ラシ",
    "文語助動詞-ラム",
    "文語助動詞-リ",
    "文語助動詞-ンス",
    "文語四段-カ行",
    "文語四段-ガ行",
    "文語四段-サ行",
    "文語四段-タ行",
    "文語四段-ハ行",
    "文語四段-バ行",
    "文語四段-マ行",
    "文語四段-ラ行",
    "文語形容詞-ク",
    "文語形容詞-シク",
    "無変化型",
]

CONJUGATION_TYPES_EN = [
    "*",

    # Irregulars
    "Ka row irregular case",
    "Sa row irregular case",

    # Ichidan
    "Kami Ichidan - A row",
    "Kami Ichidan - Ka row",
    "Kami Ichidan - Ga row",
    "Kami Ichidan - Za row",
    "Kami Ichidan - Ta row",
    "Kami Ichidan - Na row",
    "Kami Ichidan - Ha row",
    "Kami Ichidan - Ba row",
    "Kami Ichidan - Ma row",
    "Kami Ichidan - Ra row",
    "Shimo Ichidan - A row",
    "Shimo Ichidan - Ka row",
    "Shimo Ichidan - Ga row",
    "Shimo Ichidan - Sa row",
    "Shimo Ichidan - Za row",
    "Shimo Ichidan - Ta row",
    "Shimo Ichidan - Da row",
    "Shimo Ichidan - Na row",
    "Shimo Ichidan - Ha row",
    "Shimo Ichidan - Ba row",
    "Shimo Ichidan - Ma row",
    "Shimo Ichidan - Ra row",

    # Godan
    "Godan - Ka row",
    "Godan - Ga row",
    "Godan - Sa row",
    "Godan - Ta row",
    "Godan - Na row",
    "Godan - Ba row",
    "Godan - Ma row",
    "Godan - Ra row",
    "Godan - Waa row",

    # Auxiliaries
    "Auxiliary verb - Ja",
    "Auxiliary verb - Ta",
    "Auxiliary verb - Da",
    "Auxiliary verb - Tai",
    "Auxiliary verb - Desu",
    "Auxiliary verb - Dosu",
    "Auxiliary verb - Nai",
    "Auxiliary verb - Nanda",
    "Auxiliary verb - Nu",
    "Auxiliary verb - Hen",
    "Auxiliary verb - Mai",
    "Auxiliary verb - Masu",
    "Auxiliary verb - Ya",
    "Auxiliary verb - Yasu",
    "Auxiliary verb - Rashii",
    "Auxiliary verb - Reru",

    # Adjectival
    "Adjective",

    # Classical Japanese
    "Classical Japanese Ka row irregular",
    "Classical Japanese Sa row irregular",
    "Classical Japanese Na row irregular",
    "Classical Japanese Ra row irregular",
    "Classical Japanese Kami Ichidan - Na row",
    "Classical Japanese Kami Ichidan - Ma row",
    "Classical Japanese Kami Ichidan - Wa row",
    "Classical Japanese Kami Nidan - Ta row",
    "Classical Japanese Kami Nidan - Da row",
    "Classical Japanese Kami Nidan - Ha row",
    "Classical Japanese Kami Nidan - Ba row",
    "Classical Japanese Kami Nidan - Ya row",
    "Classical Japanese Kami Nidan - Ra row",
    "Classical Japanese Shimo Nidan - A row",
    "Classical Japanese Shimo Nidan - Ka row",
    "Classical Japanese Shimo Nidan - Ga row",
    "Classical Japanese Shimo Nidan - Sa row",
    "Classical Japanese Shimo Nidan - Za row",
    "Classical Japanese Shimo Nidan - Ta row",
    "Classical Japanese Shimo Nidan - Da row",
    "Classical Japanese Shimo Nidan - Na row",
    "Classical Japanese Shimo Nidan - Ha row",
    "Classical Japanese Shimo Nidan - Ba row",
    "Classical Japanese Shimo Nidan - Ma row",
    "Classical Japanese Shimo Nidan - Ya row",
    "Classical Japanese Shimo Nidan - Ra row",
    "Classical Japanese Shimo Nidan - Wa row",
    "Classical Japanese auxiliary verb - Ki",
    "Classical Japanese auxiliary verb - Kemu",
    "Classical Japanese auxiliary verb - Keri",
    "Classical Japanese auxiliary verb - Gotoshi",
    "Classical Japanese auxiliary verb - Zamasu",
    "Classical Japanese auxiliary verb - Zans",
    "Classical Japanese auxiliary verb - Ji",
    "Classical Japanese auxiliary verb - Zu",
    "Classical Japanese auxiliary verb - Tari - perfect",
    "Classical Japanese auxiliary verb - Tari - assertive",
    "Classical Japanese auxiliary verb - Tsu",
    "Classical Japanese auxiliary verb - Nari - hearsay",
    "Classical Japanese auxiliary verb - Nari - assertive",
    "Classical Japanese auxiliary verb - Nu",
    "Classical Japanese auxiliary verb - Beshi",
    "Classical Japanese auxiliary verb - Maji",
    "Classical Japanese auxiliary verb - Mu",
    "Classical Japanese auxiliary verb - Rashi",
    "Classical Japanese auxiliary verb - Ram",
    "Classical Japanese auxiliary verb - Ri",
    "Classical Japanese auxiliary verb - Nsu",
    "Classical Japanese Yodan - Ka row",
    "Classical Japanese Yodan - Ga row",
    "Classical Japanese Yodan - Sa row",
    "Classical Japanese Yodan - Ta row",
    "Classical Japanese Yodan - Ha row",
    "Classical Japanese Yodan - Ba row",
    "Classical Japanese Yodan - Ma row",
    "Classical Japanese Yodan - Ra row",
    "Classical Japanese adjective - Ku",
    "Classical Japanese adjective - Shiku",
    "Unchanging form",
]

CONJUGATION_FORMS_JP = [
    "*",
    "ク語法",

    # Conditional
    "仮定形-一般",
    "仮定形-融合",

    # Imperative
    "命令形",

    # Perfect / Hypothetical
    "已然形-一般",
    "已然形-補助",

    # Conjectural
    "意志推量形",

    # Imperfect
    "未然形-サ",
    "未然形-セ",
    "未然形-一般",
    "未然形-撥音便",
    "未然形-補助",

    # Attributive / Finalizing (Literary)
    "終止形-ウ音便",
    "終止形-一般",
    "終止形-促音便",
    "終止形-撥音便",
    "終止形-補助",

    # Stem
    "語幹-サ",
    "語幹-一般",

    # Attributive (Spoken)
    "連体形-イ音便",
    "連体形-ウ音便",
    "連体形-一般",
    "連体形-一般+送り仮名省略",
    "連体形-撥音便",
    "連体形-省略",
    "連体形-補助",

    # Continuative
    "連用形-イ音便",
    "連用形-イ音便+送り仮名省略",
    "連用形-ウ音便",
    "連用形-キ接続",
    "連用形-一般",
    "連用形-一般+送り仮名省略",
    "連用形-促音便",
    "連用形-撥音便",
    "連用形-省略",
    "連用形-融合",
    "連用形-補助",
    "連用形-ニ",
]

CONJUGATION_FORMS_EN = [
    "*",
    "Ku Grammar",

    # Conditional
    "Conditional - General",
    "Conditional - Fusion",

    # Imperative
    "Imperative",

    # Perfect / Hypothetical
    "Perfect / Hypothetical - General",
    "Perfect / Hypothetical - Auxiliary",

    # Conjectural
    "Conjectural",

    # Imperfect
    "Imperfect - Sa",
    "Imperfect - Se",
    "Imperfect - General",
    "Imperfect - Hatsuonbin",
    "Imperfect - Auxiliary",

    # Attributive / Finalizing (Literary)
    "Final (Literary) - U sound stop",
    "Final (Literary) - General",
    "Final (Literary) - Sokuonbin",
    "Final (Literary) - Hatsuonbin",
    "Final (Literary) - Auxiliary",

    # Stem
    "Stem - Sa",
    "Stem - General",

    # Attributive (Spoken)
    "Attributive - I sound stop",
    "Attributive - U sound stop",
    "Attributive - General",
    "Attributive - General + Okirigana omitted",
    "Attributive - Hatsuonbin",
    "Attributive - Omission",
    "Attributive - Auxiliary",

    # Continuative
    "Continuative - I sound adjustment",
    "Continuative - I sound adjustment + Okirigana omitted",
    "Continuative - U sound adjustment",
    "Continuative - Ki connection",
    "Continuative - General",
    "Continuative - General + Okirigana omitted",
    "Continuative - Sokuonbin",
    "Continuative - Hatsuonbin",
    "Continuative - Omission",
    "Continuative - Fusion",
    "Continuative - Auxiliary",
    "Continuative - Ni",
]


AUXILIARY_SEMANTICS = {
    "Auxiliary verb - Ja": "BE (Inf.)",
    "Auxiliary verb - Ta": "PFV",
    "Auxiliary verb - Da": "BE (Inf.)",
    "Auxiliary verb - Tai": "DES",
    "Auxiliary verb - Desu": "BE",
    "Auxiliary verb - Dosu": "BE (Kyouto)",
    "Auxiliary verb - Nai": "NOT",
    "Auxiliary verb - Nanda": "ASSERT",
    "Auxiliary verb - Nu": "NOT",
    "Auxiliary verb - Hen": "NOT (Kansai)",
    "Auxiliary verb - Mai": "CANNOT BE",
    "Auxiliary verb - Masu": "POLITE",
    "Auxiliary verb - Ya": "BE (Dialectal)",
    "Auxiliary verb - Yasu": "MASU (Contracted)",
    "Auxiliary verb - Rashii": "-LIKE",
    "Auxiliary verb - Reru": "PASSIVE",
}


CATEGORIES_JP_EN = dict(zip(CATEGORIES_JP, CATEGORIES_EN))
CATEGORIES_EN_JP = dict(zip(CATEGORIES_EN, CATEGORIES_JP))

CONJUGATION_FORMS_JP_EN = dict(zip(CONJUGATION_FORMS_JP, CONJUGATION_FORMS_EN))
CONJUGATION_FORMS_EN_JP = dict(zip(CONJUGATION_FORMS_EN, CONJUGATION_FORMS_JP))

CONJUGATION_TYPES_JP_EN = dict(zip(CONJUGATION_TYPES_JP, CONJUGATION_TYPES_EN))
CONJUGATION_TYPES_EN_JP = dict(zip(CONJUGATION_TYPES_EN, CONJUGATION_TYPES_JP))
